sonar.projectKey=activity-manager
sonar.projectName=activity-manager
sonar.host.url=http://localhost:9000

sonar.sources=app,config,routes,database,resources
sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,public/build/**

sonar.sourceEncoding=UTF-8